// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: face/v1/face.proto

package facev1

import (
	v1 "github.com/Samimelki/minak-enta/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Distance metrics for face comparison.
type DistanceMetric int32

const (
	DistanceMetric_DISTANCE_METRIC_UNSPECIFIED DistanceMetric = 0
	DistanceMetric_DISTANCE_METRIC_COSINE      DistanceMetric = 1 // Cosine similarity (higher is more similar)
	DistanceMetric_DISTANCE_METRIC_EUCLIDEAN   DistanceMetric = 2 // Euclidean distance (lower is more similar)
	DistanceMetric_DISTANCE_METRIC_MANHATTAN   DistanceMetric = 3 // Manhattan distance (lower is more similar)
)

// Enum value maps for DistanceMetric.
var (
	DistanceMetric_name = map[int32]string{
		0: "DISTANCE_METRIC_UNSPECIFIED",
		1: "DISTANCE_METRIC_COSINE",
		2: "DISTANCE_METRIC_EUCLIDEAN",
		3: "DISTANCE_METRIC_MANHATTAN",
	}
	DistanceMetric_value = map[string]int32{
		"DISTANCE_METRIC_UNSPECIFIED": 0,
		"DISTANCE_METRIC_COSINE":      1,
		"DISTANCE_METRIC_EUCLIDEAN":   2,
		"DISTANCE_METRIC_MANHATTAN":   3,
	}
)

func (x DistanceMetric) Enum() *DistanceMetric {
	p := new(DistanceMetric)
	*p = x
	return p
}

func (x DistanceMetric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistanceMetric) Descriptor() protoreflect.EnumDescriptor {
	return file_face_v1_face_proto_enumTypes[0].Descriptor()
}

func (DistanceMetric) Type() protoreflect.EnumType {
	return &file_face_v1_face_proto_enumTypes[0]
}

func (x DistanceMetric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistanceMetric.Descriptor instead.
func (DistanceMetric) EnumDescriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{0}
}

// Request to extract face embedding from an image.
type ExtractEmbeddingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Image data (JPEG or PNG).
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// Maximum number of faces to process (default: 1).
	MaxFaces int32 `protobuf:"varint,3,opt,name=max_faces,json=maxFaces,proto3" json:"max_faces,omitempty"`
	// Minimum face detection confidence threshold (0.0-1.0).
	MinConfidence float32 `protobuf:"fixed32,4,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractEmbeddingRequest) Reset() {
	*x = ExtractEmbeddingRequest{}
	mi := &file_face_v1_face_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractEmbeddingRequest) ProtoMessage() {}

func (x *ExtractEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*ExtractEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractEmbeddingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExtractEmbeddingRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ExtractEmbeddingRequest) GetMaxFaces() int32 {
	if x != nil {
		return x.MaxFaces
	}
	return 0
}

func (x *ExtractEmbeddingRequest) GetMinConfidence() float32 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

// Response from embedding extraction.
type ExtractEmbeddingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processing status.
	Status v1.ProcessingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=minakenta.common.v1.ProcessingStatus" json:"status,omitempty"`
	// Detected faces with their embeddings.
	Faces []*FaceEmbedding `protobuf:"bytes,2,rep,name=faces,proto3" json:"faces,omitempty"`
	// Processing metadata.
	Metadata *v1.ProcessingMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Error details if processing failed.
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractEmbeddingResponse) Reset() {
	*x = ExtractEmbeddingResponse{}
	mi := &file_face_v1_face_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractEmbeddingResponse) ProtoMessage() {}

func (x *ExtractEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*ExtractEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractEmbeddingResponse) GetStatus() v1.ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return v1.ProcessingStatus(0)
}

func (x *ExtractEmbeddingResponse) GetFaces() []*FaceEmbedding {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *ExtractEmbeddingResponse) GetMetadata() *v1.ProcessingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExtractEmbeddingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Face embedding data.
type FaceEmbedding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Face identifier within the image.
	FaceId int32 `protobuf:"varint,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	// Face detection confidence (0.0-1.0).
	DetectionConfidence float32 `protobuf:"fixed32,2,opt,name=detection_confidence,json=detectionConfidence,proto3" json:"detection_confidence,omitempty"`
	// Face embedding vector (normalized).
	Embedding []float32 `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	// Face bounding box coordinates.
	BoundingBox *v1.BoundingBox `protobuf:"bytes,4,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	// Face landmarks (optional).
	Landmarks     []*Landmark `protobuf:"bytes,5,rep,name=landmarks,proto3" json:"landmarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceEmbedding) Reset() {
	*x = FaceEmbedding{}
	mi := &file_face_v1_face_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceEmbedding) ProtoMessage() {}

func (x *FaceEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceEmbedding.ProtoReflect.Descriptor instead.
func (*FaceEmbedding) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{2}
}

func (x *FaceEmbedding) GetFaceId() int32 {
	if x != nil {
		return x.FaceId
	}
	return 0
}

func (x *FaceEmbedding) GetDetectionConfidence() float32 {
	if x != nil {
		return x.DetectionConfidence
	}
	return 0
}

func (x *FaceEmbedding) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *FaceEmbedding) GetBoundingBox() *v1.BoundingBox {
	if x != nil {
		return x.BoundingBox
	}
	return nil
}

func (x *FaceEmbedding) GetLandmarks() []*Landmark {
	if x != nil {
		return x.Landmarks
	}
	return nil
}

// Facial landmark point.
type Landmark struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Landmark name (e.g., "left_eye", "nose", "mouth").
	Name          string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	X             float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Landmark) Reset() {
	*x = Landmark{}
	mi := &file_face_v1_face_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Landmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Landmark) ProtoMessage() {}

func (x *Landmark) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Landmark.ProtoReflect.Descriptor instead.
func (*Landmark) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{3}
}

func (x *Landmark) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Landmark) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Landmark) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Request to compare two face embeddings.
type CompareFacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// First face embedding.
	Embedding1 []float32 `protobuf:"fixed32,2,rep,packed,name=embedding1,proto3" json:"embedding1,omitempty"`
	// Second face embedding.
	Embedding2 []float32 `protobuf:"fixed32,3,rep,packed,name=embedding2,proto3" json:"embedding2,omitempty"`
	// Distance metric to use.
	Metric        DistanceMetric `protobuf:"varint,4,opt,name=metric,proto3,enum=minakenta.face.v1.DistanceMetric" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareFacesRequest) Reset() {
	*x = CompareFacesRequest{}
	mi := &file_face_v1_face_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareFacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareFacesRequest) ProtoMessage() {}

func (x *CompareFacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareFacesRequest.ProtoReflect.Descriptor instead.
func (*CompareFacesRequest) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{4}
}

func (x *CompareFacesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CompareFacesRequest) GetEmbedding1() []float32 {
	if x != nil {
		return x.Embedding1
	}
	return nil
}

func (x *CompareFacesRequest) GetEmbedding2() []float32 {
	if x != nil {
		return x.Embedding2
	}
	return nil
}

func (x *CompareFacesRequest) GetMetric() DistanceMetric {
	if x != nil {
		return x.Metric
	}
	return DistanceMetric_DISTANCE_METRIC_UNSPECIFIED
}

// Response from face comparison.
type CompareFacesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Similarity score (0.0-1.0, higher is more similar).
	SimilarityScore float32 `protobuf:"fixed32,1,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	// Distance value (interpretation depends on metric).
	Distance float32 `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	// Confidence in the comparison result (0.0-1.0).
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Processing metadata.
	Metadata *v1.ProcessingMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Error details if comparison failed.
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompareFacesResponse) Reset() {
	*x = CompareFacesResponse{}
	mi := &file_face_v1_face_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompareFacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareFacesResponse) ProtoMessage() {}

func (x *CompareFacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareFacesResponse.ProtoReflect.Descriptor instead.
func (*CompareFacesResponse) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{5}
}

func (x *CompareFacesResponse) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *CompareFacesResponse) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *CompareFacesResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CompareFacesResponse) GetMetadata() *v1.ProcessingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CompareFacesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request to detect faces in an image.
type DetectFacesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Image data (JPEG or PNG).
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// Maximum number of faces to detect.
	MaxFaces int32 `protobuf:"varint,3,opt,name=max_faces,json=maxFaces,proto3" json:"max_faces,omitempty"`
	// Minimum detection confidence threshold (0.0-1.0).
	MinConfidence float32 `protobuf:"fixed32,4,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectFacesRequest) Reset() {
	*x = DetectFacesRequest{}
	mi := &file_face_v1_face_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectFacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectFacesRequest) ProtoMessage() {}

func (x *DetectFacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectFacesRequest.ProtoReflect.Descriptor instead.
func (*DetectFacesRequest) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{6}
}

func (x *DetectFacesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DetectFacesRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *DetectFacesRequest) GetMaxFaces() int32 {
	if x != nil {
		return x.MaxFaces
	}
	return 0
}

func (x *DetectFacesRequest) GetMinConfidence() float32 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

// Response from face detection.
type DetectFacesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processing status.
	Status v1.ProcessingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=minakenta.common.v1.ProcessingStatus" json:"status,omitempty"`
	// Detected faces.
	Faces []*DetectedFace `protobuf:"bytes,2,rep,name=faces,proto3" json:"faces,omitempty"`
	// Processing metadata.
	Metadata *v1.ProcessingMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Error details if detection failed.
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectFacesResponse) Reset() {
	*x = DetectFacesResponse{}
	mi := &file_face_v1_face_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectFacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectFacesResponse) ProtoMessage() {}

func (x *DetectFacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectFacesResponse.ProtoReflect.Descriptor instead.
func (*DetectFacesResponse) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{7}
}

func (x *DetectFacesResponse) GetStatus() v1.ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return v1.ProcessingStatus(0)
}

func (x *DetectFacesResponse) GetFaces() []*DetectedFace {
	if x != nil {
		return x.Faces
	}
	return nil
}

func (x *DetectFacesResponse) GetMetadata() *v1.ProcessingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DetectFacesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Detected face information (without embedding).
type DetectedFace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Face identifier within the image.
	FaceId int32 `protobuf:"varint,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	// Detection confidence (0.0-1.0).
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Face bounding box coordinates.
	BoundingBox *v1.BoundingBox `protobuf:"bytes,3,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	// Face landmarks (optional).
	Landmarks     []*Landmark `protobuf:"bytes,4,rep,name=landmarks,proto3" json:"landmarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectedFace) Reset() {
	*x = DetectedFace{}
	mi := &file_face_v1_face_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedFace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedFace) ProtoMessage() {}

func (x *DetectedFace) ProtoReflect() protoreflect.Message {
	mi := &file_face_v1_face_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedFace.ProtoReflect.Descriptor instead.
func (*DetectedFace) Descriptor() ([]byte, []int) {
	return file_face_v1_face_proto_rawDescGZIP(), []int{8}
}

func (x *DetectedFace) GetFaceId() int32 {
	if x != nil {
		return x.FaceId
	}
	return 0
}

func (x *DetectedFace) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectedFace) GetBoundingBox() *v1.BoundingBox {
	if x != nil {
		return x.BoundingBox
	}
	return nil
}

func (x *DetectedFace) GetLandmarks() []*Landmark {
	if x != nil {
		return x.Landmarks
	}
	return nil
}

var File_face_v1_face_proto protoreflect.FileDescriptor

const file_face_v1_face_proto_rawDesc = "" +
	"\n" +
	"\x12face/v1/face.proto\x12\x11minakenta.face.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\x9b\x01\n" +
	"\x17ExtractEmbeddingRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x1b\n" +
	"\tmax_faces\x18\x03 \x01(\x05R\bmaxFaces\x12%\n" +
	"\x0emin_confidence\x18\x04 \x01(\x02R\rminConfidence\"\xfb\x01\n" +
	"\x18ExtractEmbeddingResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.minakenta.common.v1.ProcessingStatusR\x06status\x126\n" +
	"\x05faces\x18\x02 \x03(\v2 .minakenta.face.v1.FaceEmbeddingR\x05faces\x12C\n" +
	"\bmetadata\x18\x03 \x01(\v2'.minakenta.common.v1.ProcessingMetadataR\bmetadata\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xf9\x01\n" +
	"\rFaceEmbedding\x12\x17\n" +
	"\aface_id\x18\x01 \x01(\x05R\x06faceId\x121\n" +
	"\x14detection_confidence\x18\x02 \x01(\x02R\x13detectionConfidence\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\x12C\n" +
	"\fbounding_box\x18\x04 \x01(\v2 .minakenta.common.v1.BoundingBoxR\vboundingBox\x129\n" +
	"\tlandmarks\x18\x05 \x03(\v2\x1b.minakenta.face.v1.LandmarkR\tlandmarks\":\n" +
	"\bLandmark\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\"\xaf\x01\n" +
	"\x13CompareFacesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"embedding1\x18\x02 \x03(\x02R\n" +
	"embedding1\x12\x1e\n" +
	"\n" +
	"embedding2\x18\x03 \x03(\x02R\n" +
	"embedding2\x129\n" +
	"\x06metric\x18\x04 \x01(\x0e2!.minakenta.face.v1.DistanceMetricR\x06metric\"\xe7\x01\n" +
	"\x14CompareFacesResponse\x12)\n" +
	"\x10similarity_score\x18\x01 \x01(\x02R\x0fsimilarityScore\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12C\n" +
	"\bmetadata\x18\x04 \x01(\v2'.minakenta.common.v1.ProcessingMetadataR\bmetadata\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x96\x01\n" +
	"\x12DetectFacesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x1b\n" +
	"\tmax_faces\x18\x03 \x01(\x05R\bmaxFaces\x12%\n" +
	"\x0emin_confidence\x18\x04 \x01(\x02R\rminConfidence\"\xf5\x01\n" +
	"\x13DetectFacesResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.minakenta.common.v1.ProcessingStatusR\x06status\x125\n" +
	"\x05faces\x18\x02 \x03(\v2\x1f.minakenta.face.v1.DetectedFaceR\x05faces\x12C\n" +
	"\bmetadata\x18\x03 \x01(\v2'.minakenta.common.v1.ProcessingMetadataR\bmetadata\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xc7\x01\n" +
	"\fDetectedFace\x12\x17\n" +
	"\aface_id\x18\x01 \x01(\x05R\x06faceId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12C\n" +
	"\fbounding_box\x18\x03 \x01(\v2 .minakenta.common.v1.BoundingBoxR\vboundingBox\x129\n" +
	"\tlandmarks\x18\x04 \x03(\v2\x1b.minakenta.face.v1.LandmarkR\tlandmarks*\x8b\x01\n" +
	"\x0eDistanceMetric\x12\x1f\n" +
	"\x1bDISTANCE_METRIC_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DISTANCE_METRIC_COSINE\x10\x01\x12\x1d\n" +
	"\x19DISTANCE_METRIC_EUCLIDEAN\x10\x02\x12\x1d\n" +
	"\x19DISTANCE_METRIC_MANHATTAN\x10\x032\xb9\x02\n" +
	"\vFaceService\x12k\n" +
	"\x10ExtractEmbedding\x12*.minakenta.face.v1.ExtractEmbeddingRequest\x1a+.minakenta.face.v1.ExtractEmbeddingResponse\x12_\n" +
	"\fCompareFaces\x12&.minakenta.face.v1.CompareFacesRequest\x1a'.minakenta.face.v1.CompareFacesResponse\x12\\\n" +
	"\vDetectFaces\x12%.minakenta.face.v1.DetectFacesRequest\x1a&.minakenta.face.v1.DetectFacesResponseB\xbc\x01\n" +
	"\x15com.minakenta.face.v1B\tFaceProtoP\x01Z2github.com/Samimelki/minak-enta/api/face/v1;facev1\xa2\x02\x03MFX\xaa\x02\x11Minakenta.Face.V1\xca\x02\x11Minakenta\\Face\\V1\xe2\x02\x1dMinakenta\\Face\\V1\\GPBMetadata\xea\x02\x13Minakenta::Face::V1b\x06proto3"

var (
	file_face_v1_face_proto_rawDescOnce sync.Once
	file_face_v1_face_proto_rawDescData []byte
)

func file_face_v1_face_proto_rawDescGZIP() []byte {
	file_face_v1_face_proto_rawDescOnce.Do(func() {
		file_face_v1_face_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_face_v1_face_proto_rawDesc), len(file_face_v1_face_proto_rawDesc)))
	})
	return file_face_v1_face_proto_rawDescData
}

var file_face_v1_face_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_face_v1_face_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_face_v1_face_proto_goTypes = []any{
	(DistanceMetric)(0),              // 0: minakenta.face.v1.DistanceMetric
	(*ExtractEmbeddingRequest)(nil),  // 1: minakenta.face.v1.ExtractEmbeddingRequest
	(*ExtractEmbeddingResponse)(nil), // 2: minakenta.face.v1.ExtractEmbeddingResponse
	(*FaceEmbedding)(nil),            // 3: minakenta.face.v1.FaceEmbedding
	(*Landmark)(nil),                 // 4: minakenta.face.v1.Landmark
	(*CompareFacesRequest)(nil),      // 5: minakenta.face.v1.CompareFacesRequest
	(*CompareFacesResponse)(nil),     // 6: minakenta.face.v1.CompareFacesResponse
	(*DetectFacesRequest)(nil),       // 7: minakenta.face.v1.DetectFacesRequest
	(*DetectFacesResponse)(nil),      // 8: minakenta.face.v1.DetectFacesResponse
	(*DetectedFace)(nil),             // 9: minakenta.face.v1.DetectedFace
	(v1.ProcessingStatus)(0),         // 10: minakenta.common.v1.ProcessingStatus
	(*v1.ProcessingMetadata)(nil),    // 11: minakenta.common.v1.ProcessingMetadata
	(*v1.BoundingBox)(nil),           // 12: minakenta.common.v1.BoundingBox
}
var file_face_v1_face_proto_depIdxs = []int32{
	10, // 0: minakenta.face.v1.ExtractEmbeddingResponse.status:type_name -> minakenta.common.v1.ProcessingStatus
	3,  // 1: minakenta.face.v1.ExtractEmbeddingResponse.faces:type_name -> minakenta.face.v1.FaceEmbedding
	11, // 2: minakenta.face.v1.ExtractEmbeddingResponse.metadata:type_name -> minakenta.common.v1.ProcessingMetadata
	12, // 3: minakenta.face.v1.FaceEmbedding.bounding_box:type_name -> minakenta.common.v1.BoundingBox
	4,  // 4: minakenta.face.v1.FaceEmbedding.landmarks:type_name -> minakenta.face.v1.Landmark
	0,  // 5: minakenta.face.v1.CompareFacesRequest.metric:type_name -> minakenta.face.v1.DistanceMetric
	11, // 6: minakenta.face.v1.CompareFacesResponse.metadata:type_name -> minakenta.common.v1.ProcessingMetadata
	10, // 7: minakenta.face.v1.DetectFacesResponse.status:type_name -> minakenta.common.v1.ProcessingStatus
	9,  // 8: minakenta.face.v1.DetectFacesResponse.faces:type_name -> minakenta.face.v1.DetectedFace
	11, // 9: minakenta.face.v1.DetectFacesResponse.metadata:type_name -> minakenta.common.v1.ProcessingMetadata
	12, // 10: minakenta.face.v1.DetectedFace.bounding_box:type_name -> minakenta.common.v1.BoundingBox
	4,  // 11: minakenta.face.v1.DetectedFace.landmarks:type_name -> minakenta.face.v1.Landmark
	1,  // 12: minakenta.face.v1.FaceService.ExtractEmbedding:input_type -> minakenta.face.v1.ExtractEmbeddingRequest
	5,  // 13: minakenta.face.v1.FaceService.CompareFaces:input_type -> minakenta.face.v1.CompareFacesRequest
	7,  // 14: minakenta.face.v1.FaceService.DetectFaces:input_type -> minakenta.face.v1.DetectFacesRequest
	2,  // 15: minakenta.face.v1.FaceService.ExtractEmbedding:output_type -> minakenta.face.v1.ExtractEmbeddingResponse
	6,  // 16: minakenta.face.v1.FaceService.CompareFaces:output_type -> minakenta.face.v1.CompareFacesResponse
	8,  // 17: minakenta.face.v1.FaceService.DetectFaces:output_type -> minakenta.face.v1.DetectFacesResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_face_v1_face_proto_init() }
func file_face_v1_face_proto_init() {
	if File_face_v1_face_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_face_v1_face_proto_rawDesc), len(file_face_v1_face_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_face_v1_face_proto_goTypes,
		DependencyIndexes: file_face_v1_face_proto_depIdxs,
		EnumInfos:         file_face_v1_face_proto_enumTypes,
		MessageInfos:      file_face_v1_face_proto_msgTypes,
	}.Build()
	File_face_v1_face_proto = out.File
	file_face_v1_face_proto_goTypes = nil
	file_face_v1_face_proto_depIdxs = nil
}
