// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: face/v1/face.proto

package facev1

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// FaceServiceServer is the server API for FaceService service.
type FaceServiceServer interface {
	ExtractEmbedding(context.Context, *ExtractEmbeddingRequest) (*ExtractEmbeddingResponse, error)
	CompareFaces(context.Context, *CompareFacesRequest) (*CompareFacesResponse, error)
	DetectFaces(context.Context, *DetectFacesRequest) (*DetectFacesResponse, error)
}

// RegisterFaceServiceServer registers the HTTP handlers for service FaceService to the given mux.
func RegisterFaceServiceServer(server FaceServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getFaceServiceHeaders()

	methodHeaders := getExtractEmbeddingHeaders()
	extractEmbeddingHandler := BindingMiddleware[ExtractEmbeddingRequest](
		genericHandler(server.ExtractEmbedding), serviceHeaders, methodHeaders,
	)

	config.mux.Handle("POST /facev1/extract_embedding", extractEmbeddingHandler)

	methodHeaders = getCompareFacesHeaders()
	compareFacesHandler := BindingMiddleware[CompareFacesRequest](
		genericHandler(server.CompareFaces), serviceHeaders, methodHeaders,
	)

	config.mux.Handle("POST /facev1/compare_faces", compareFacesHandler)

	methodHeaders = getDetectFacesHeaders()
	detectFacesHandler := BindingMiddleware[DetectFacesRequest](
		genericHandler(server.DetectFaces), serviceHeaders, methodHeaders,
	)

	config.mux.Handle("POST /facev1/detect_faces", detectFacesHandler)

	return nil
}

// getFaceServiceHeaders returns the service-level required headers for FaceService
func getFaceServiceHeaders() []*sebufhttp.Header {
	return nil
}

// getExtractEmbeddingHeaders returns the method-level required headers for ExtractEmbedding
func getExtractEmbeddingHeaders() []*sebufhttp.Header {
	return nil
}

// getCompareFacesHeaders returns the method-level required headers for CompareFaces
func getCompareFacesHeaders() []*sebufhttp.Header {
	return nil
}

// getDetectFacesHeaders returns the method-level required headers for DetectFaces
func getDetectFacesHeaders() []*sebufhttp.Header {
	return nil
}
