// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: liveness/v1/liveness.proto

package livenessv1

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// LivenessServiceServer is the server API for LivenessService service.
type LivenessServiceServer interface {
	DetectLiveness(context.Context, *DetectLivenessRequest) (*DetectLivenessResponse, error)
	AnalyzeVideoSequence(context.Context, *AnalyzeVideoSequenceRequest) (*AnalyzeVideoSequenceResponse, error)
}

// RegisterLivenessServiceServer registers the HTTP handlers for service LivenessService to the given mux.
func RegisterLivenessServiceServer(server LivenessServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getLivenessServiceHeaders()

	methodHeaders := getDetectLivenessHeaders()
	detectLivenessHandler := BindingMiddleware[DetectLivenessRequest](
		genericHandler(server.DetectLiveness), serviceHeaders, methodHeaders,
	)

	config.mux.Handle("POST /livenessv1/detect_liveness", detectLivenessHandler)

	methodHeaders = getAnalyzeVideoSequenceHeaders()
	analyzeVideoSequenceHandler := BindingMiddleware[AnalyzeVideoSequenceRequest](
		genericHandler(server.AnalyzeVideoSequence), serviceHeaders, methodHeaders,
	)

	config.mux.Handle("POST /livenessv1/analyze_video_sequence", analyzeVideoSequenceHandler)

	return nil
}

// getLivenessServiceHeaders returns the service-level required headers for LivenessService
func getLivenessServiceHeaders() []*sebufhttp.Header {
	return nil
}

// getDetectLivenessHeaders returns the method-level required headers for DetectLiveness
func getDetectLivenessHeaders() []*sebufhttp.Header {
	return nil
}

// getAnalyzeVideoSequenceHeaders returns the method-level required headers for AnalyzeVideoSequence
func getAnalyzeVideoSequenceHeaders() []*sebufhttp.Header {
	return nil
}
