// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: liveness/v1/liveness.proto

package livenessv1

import (
	v1 "github.com/Samimelki/minak-enta/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to detect liveness in a single image.
type DetectLivenessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Selfie image data (JPEG or PNG).
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// Challenge type used (if any).
	ChallengeType string `protobuf:"bytes,3,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"`
	// Expected user actions (e.g., "blink", "smile", "turn_head").
	ExpectedActions []string `protobuf:"bytes,4,rep,name=expected_actions,json=expectedActions,proto3" json:"expected_actions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetectLivenessRequest) Reset() {
	*x = DetectLivenessRequest{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectLivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectLivenessRequest) ProtoMessage() {}

func (x *DetectLivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectLivenessRequest.ProtoReflect.Descriptor instead.
func (*DetectLivenessRequest) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{0}
}

func (x *DetectLivenessRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DetectLivenessRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *DetectLivenessRequest) GetChallengeType() string {
	if x != nil {
		return x.ChallengeType
	}
	return ""
}

func (x *DetectLivenessRequest) GetExpectedActions() []string {
	if x != nil {
		return x.ExpectedActions
	}
	return nil
}

// Response from liveness detection.
type DetectLivenessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processing status.
	Status v1.ProcessingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=minakenta.common.v1.ProcessingStatus" json:"status,omitempty"`
	// Overall liveness score (0.0-1.0, higher is more likely live).
	LivenessScore float32 `protobuf:"fixed32,2,opt,name=liveness_score,json=livenessScore,proto3" json:"liveness_score,omitempty"`
	// Confidence in the liveness assessment (0.0-1.0).
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Detailed analysis results.
	Analysis *LivenessAnalysis `protobuf:"bytes,4,opt,name=analysis,proto3" json:"analysis,omitempty"`
	// Processing metadata.
	Metadata *v1.ProcessingMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Error details if detection failed.
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectLivenessResponse) Reset() {
	*x = DetectLivenessResponse{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectLivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectLivenessResponse) ProtoMessage() {}

func (x *DetectLivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectLivenessResponse.ProtoReflect.Descriptor instead.
func (*DetectLivenessResponse) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{1}
}

func (x *DetectLivenessResponse) GetStatus() v1.ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return v1.ProcessingStatus(0)
}

func (x *DetectLivenessResponse) GetLivenessScore() float32 {
	if x != nil {
		return x.LivenessScore
	}
	return 0
}

func (x *DetectLivenessResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectLivenessResponse) GetAnalysis() *LivenessAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *DetectLivenessResponse) GetMetadata() *v1.ProcessingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DetectLivenessResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Detailed liveness analysis results.
type LivenessAnalysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Face detection results.
	FaceDetection *FaceDetection `protobuf:"bytes,1,opt,name=face_detection,json=faceDetection,proto3" json:"face_detection,omitempty"`
	// Spoofing detection results.
	SpoofingDetection *SpoofingDetection `protobuf:"bytes,2,opt,name=spoofing_detection,json=spoofingDetection,proto3" json:"spoofing_detection,omitempty"`
	// Motion analysis (if available).
	MotionAnalysis *MotionAnalysis `protobuf:"bytes,3,opt,name=motion_analysis,json=motionAnalysis,proto3" json:"motion_analysis,omitempty"`
	// Quality assessment.
	QualityAssessment *QualityAssessment `protobuf:"bytes,4,opt,name=quality_assessment,json=qualityAssessment,proto3" json:"quality_assessment,omitempty"`
	// Attack type detection (if spoofing detected).
	AttackDetection *AttackTypeDetection `protobuf:"bytes,5,opt,name=attack_detection,json=attackDetection,proto3" json:"attack_detection,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LivenessAnalysis) Reset() {
	*x = LivenessAnalysis{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessAnalysis) ProtoMessage() {}

func (x *LivenessAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessAnalysis.ProtoReflect.Descriptor instead.
func (*LivenessAnalysis) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{2}
}

func (x *LivenessAnalysis) GetFaceDetection() *FaceDetection {
	if x != nil {
		return x.FaceDetection
	}
	return nil
}

func (x *LivenessAnalysis) GetSpoofingDetection() *SpoofingDetection {
	if x != nil {
		return x.SpoofingDetection
	}
	return nil
}

func (x *LivenessAnalysis) GetMotionAnalysis() *MotionAnalysis {
	if x != nil {
		return x.MotionAnalysis
	}
	return nil
}

func (x *LivenessAnalysis) GetQualityAssessment() *QualityAssessment {
	if x != nil {
		return x.QualityAssessment
	}
	return nil
}

func (x *LivenessAnalysis) GetAttackDetection() *AttackTypeDetection {
	if x != nil {
		return x.AttackDetection
	}
	return nil
}

// Face detection results.
type FaceDetection struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FaceDetected        bool                   `protobuf:"varint,1,opt,name=face_detected,json=faceDetected,proto3" json:"face_detected,omitempty"`
	DetectionConfidence float32                `protobuf:"fixed32,2,opt,name=detection_confidence,json=detectionConfidence,proto3" json:"detection_confidence,omitempty"`
	FaceBounds          *v1.BoundingBox        `protobuf:"bytes,3,opt,name=face_bounds,json=faceBounds,proto3" json:"face_bounds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FaceDetection) Reset() {
	*x = FaceDetection{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceDetection) ProtoMessage() {}

func (x *FaceDetection) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceDetection.ProtoReflect.Descriptor instead.
func (*FaceDetection) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{3}
}

func (x *FaceDetection) GetFaceDetected() bool {
	if x != nil {
		return x.FaceDetected
	}
	return false
}

func (x *FaceDetection) GetDetectionConfidence() float32 {
	if x != nil {
		return x.DetectionConfidence
	}
	return 0
}

func (x *FaceDetection) GetFaceBounds() *v1.BoundingBox {
	if x != nil {
		return x.FaceBounds
	}
	return nil
}

// Spoofing detection results.
type SpoofingDetection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Probability of spoofing attack (0.0-1.0).
	SpoofingProbability float32 `protobuf:"fixed32,1,opt,name=spoofing_probability,json=spoofingProbability,proto3" json:"spoofing_probability,omitempty"`
	// Detected spoofing methods.
	DetectedMethods []string `protobuf:"bytes,2,rep,name=detected_methods,json=detectedMethods,proto3" json:"detected_methods,omitempty"`
	// Anti-spoofing scores for different attack types.
	AntiSpoofingScores map[string]float32 `protobuf:"bytes,3,rep,name=anti_spoofing_scores,json=antiSpoofingScores,proto3" json:"anti_spoofing_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SpoofingDetection) Reset() {
	*x = SpoofingDetection{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpoofingDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpoofingDetection) ProtoMessage() {}

func (x *SpoofingDetection) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpoofingDetection.ProtoReflect.Descriptor instead.
func (*SpoofingDetection) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{4}
}

func (x *SpoofingDetection) GetSpoofingProbability() float32 {
	if x != nil {
		return x.SpoofingProbability
	}
	return 0
}

func (x *SpoofingDetection) GetDetectedMethods() []string {
	if x != nil {
		return x.DetectedMethods
	}
	return nil
}

func (x *SpoofingDetection) GetAntiSpoofingScores() map[string]float32 {
	if x != nil {
		return x.AntiSpoofingScores
	}
	return nil
}

// Motion analysis results.
type MotionAnalysis struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MotionDetected bool                   `protobuf:"varint,1,opt,name=motion_detected,json=motionDetected,proto3" json:"motion_detected,omitempty"`
	MotionScore    float32                `protobuf:"fixed32,2,opt,name=motion_score,json=motionScore,proto3" json:"motion_score,omitempty"`
	// Motion type (e.g., "blink", "head_turn", "expression_change").
	MotionType    string `protobuf:"bytes,3,opt,name=motion_type,json=motionType,proto3" json:"motion_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MotionAnalysis) Reset() {
	*x = MotionAnalysis{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotionAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotionAnalysis) ProtoMessage() {}

func (x *MotionAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotionAnalysis.ProtoReflect.Descriptor instead.
func (*MotionAnalysis) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{5}
}

func (x *MotionAnalysis) GetMotionDetected() bool {
	if x != nil {
		return x.MotionDetected
	}
	return false
}

func (x *MotionAnalysis) GetMotionScore() float32 {
	if x != nil {
		return x.MotionScore
	}
	return 0
}

func (x *MotionAnalysis) GetMotionType() string {
	if x != nil {
		return x.MotionType
	}
	return ""
}

// Image quality assessment.
type QualityAssessment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall quality (0.0-1.0).
	OverallQuality float32 `protobuf:"fixed32,1,opt,name=overall_quality,json=overallQuality,proto3" json:"overall_quality,omitempty"`
	// Brightness score (0.0-1.0).
	BrightnessScore float32 `protobuf:"fixed32,2,opt,name=brightness_score,json=brightnessScore,proto3" json:"brightness_score,omitempty"`
	// Sharpness score (0.0-1.0).
	SharpnessScore float32 `protobuf:"fixed32,3,opt,name=sharpness_score,json=sharpnessScore,proto3" json:"sharpness_score,omitempty"`
	// Contrast score (0.0-1.0).
	ContrastScore float32 `protobuf:"fixed32,4,opt,name=contrast_score,json=contrastScore,proto3" json:"contrast_score,omitempty"`
	// Noise score (0.0-1.0, lower is better).
	NoiseScore float32 `protobuf:"fixed32,5,opt,name=noise_score,json=noiseScore,proto3" json:"noise_score,omitempty"`
	// Specific quality issues detected.
	QualityIssues []string `protobuf:"bytes,6,rep,name=quality_issues,json=qualityIssues,proto3" json:"quality_issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityAssessment) Reset() {
	*x = QualityAssessment{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityAssessment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityAssessment) ProtoMessage() {}

func (x *QualityAssessment) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityAssessment.ProtoReflect.Descriptor instead.
func (*QualityAssessment) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{6}
}

func (x *QualityAssessment) GetOverallQuality() float32 {
	if x != nil {
		return x.OverallQuality
	}
	return 0
}

func (x *QualityAssessment) GetBrightnessScore() float32 {
	if x != nil {
		return x.BrightnessScore
	}
	return 0
}

func (x *QualityAssessment) GetSharpnessScore() float32 {
	if x != nil {
		return x.SharpnessScore
	}
	return 0
}

func (x *QualityAssessment) GetContrastScore() float32 {
	if x != nil {
		return x.ContrastScore
	}
	return 0
}

func (x *QualityAssessment) GetNoiseScore() float32 {
	if x != nil {
		return x.NoiseScore
	}
	return 0
}

func (x *QualityAssessment) GetQualityIssues() []string {
	if x != nil {
		return x.QualityIssues
	}
	return nil
}

// Attack type detection.
type AttackTypeDetection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary attack type detected.
	PrimaryAttackType string `protobuf:"bytes,1,opt,name=primary_attack_type,json=primaryAttackType,proto3" json:"primary_attack_type,omitempty"`
	// Confidence scores for different attack types.
	AttackTypeConfidences map[string]float32 `protobuf:"bytes,2,rep,name=attack_type_confidences,json=attackTypeConfidences,proto3" json:"attack_type_confidences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AttackTypeDetection) Reset() {
	*x = AttackTypeDetection{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackTypeDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackTypeDetection) ProtoMessage() {}

func (x *AttackTypeDetection) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackTypeDetection.ProtoReflect.Descriptor instead.
func (*AttackTypeDetection) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{7}
}

func (x *AttackTypeDetection) GetPrimaryAttackType() string {
	if x != nil {
		return x.PrimaryAttackType
	}
	return ""
}

func (x *AttackTypeDetection) GetAttackTypeConfidences() map[string]float32 {
	if x != nil {
		return x.AttackTypeConfidences
	}
	return nil
}

// Request to analyze a sequence of video frames.
type AnalyzeVideoSequenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Sequence of image frames (JPEG or PNG).
	FrameData [][]byte `protobuf:"bytes,2,rep,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	// Frame timestamps (relative to sequence start).
	FrameTimestampsMs []int64 `protobuf:"varint,3,rep,packed,name=frame_timestamps_ms,json=frameTimestampsMs,proto3" json:"frame_timestamps_ms,omitempty"`
	// Challenge type used.
	ChallengeType string `protobuf:"bytes,4,opt,name=challenge_type,json=challengeType,proto3" json:"challenge_type,omitempty"`
	// Expected user actions during the sequence.
	ExpectedActions []string `protobuf:"bytes,5,rep,name=expected_actions,json=expectedActions,proto3" json:"expected_actions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeVideoSequenceRequest) Reset() {
	*x = AnalyzeVideoSequenceRequest{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoSequenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoSequenceRequest) ProtoMessage() {}

func (x *AnalyzeVideoSequenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoSequenceRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoSequenceRequest) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{8}
}

func (x *AnalyzeVideoSequenceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeVideoSequenceRequest) GetFrameData() [][]byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

func (x *AnalyzeVideoSequenceRequest) GetFrameTimestampsMs() []int64 {
	if x != nil {
		return x.FrameTimestampsMs
	}
	return nil
}

func (x *AnalyzeVideoSequenceRequest) GetChallengeType() string {
	if x != nil {
		return x.ChallengeType
	}
	return ""
}

func (x *AnalyzeVideoSequenceRequest) GetExpectedActions() []string {
	if x != nil {
		return x.ExpectedActions
	}
	return nil
}

// Response from video sequence analysis.
type AnalyzeVideoSequenceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processing status.
	Status v1.ProcessingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=minakenta.common.v1.ProcessingStatus" json:"status,omitempty"`
	// Overall liveness score (0.0-1.0).
	LivenessScore float32 `protobuf:"fixed32,2,opt,name=liveness_score,json=livenessScore,proto3" json:"liveness_score,omitempty"`
	// Confidence in the assessment (0.0-1.0).
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Per-frame analysis results.
	FrameAnalyses []*FrameAnalysis `protobuf:"bytes,4,rep,name=frame_analyses,json=frameAnalyses,proto3" json:"frame_analyses,omitempty"`
	// Sequence-level analysis.
	SequenceAnalysis *SequenceAnalysis `protobuf:"bytes,5,opt,name=sequence_analysis,json=sequenceAnalysis,proto3" json:"sequence_analysis,omitempty"`
	// Processing metadata.
	Metadata *v1.ProcessingMetadata `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Error details if analysis failed.
	ErrorMessage  string `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeVideoSequenceResponse) Reset() {
	*x = AnalyzeVideoSequenceResponse{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeVideoSequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeVideoSequenceResponse) ProtoMessage() {}

func (x *AnalyzeVideoSequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeVideoSequenceResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeVideoSequenceResponse) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{9}
}

func (x *AnalyzeVideoSequenceResponse) GetStatus() v1.ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return v1.ProcessingStatus(0)
}

func (x *AnalyzeVideoSequenceResponse) GetLivenessScore() float32 {
	if x != nil {
		return x.LivenessScore
	}
	return 0
}

func (x *AnalyzeVideoSequenceResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeVideoSequenceResponse) GetFrameAnalyses() []*FrameAnalysis {
	if x != nil {
		return x.FrameAnalyses
	}
	return nil
}

func (x *AnalyzeVideoSequenceResponse) GetSequenceAnalysis() *SequenceAnalysis {
	if x != nil {
		return x.SequenceAnalysis
	}
	return nil
}

func (x *AnalyzeVideoSequenceResponse) GetMetadata() *v1.ProcessingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalyzeVideoSequenceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Analysis results for a single frame.
type FrameAnalysis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameIndex    int32                  `protobuf:"varint,1,opt,name=frame_index,json=frameIndex,proto3" json:"frame_index,omitempty"`
	LivenessScore float32                `protobuf:"fixed32,2,opt,name=liveness_score,json=livenessScore,proto3" json:"liveness_score,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Analysis      *LivenessAnalysis      `protobuf:"bytes,4,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameAnalysis) Reset() {
	*x = FrameAnalysis{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameAnalysis) ProtoMessage() {}

func (x *FrameAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameAnalysis.ProtoReflect.Descriptor instead.
func (*FrameAnalysis) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{10}
}

func (x *FrameAnalysis) GetFrameIndex() int32 {
	if x != nil {
		return x.FrameIndex
	}
	return 0
}

func (x *FrameAnalysis) GetLivenessScore() float32 {
	if x != nil {
		return x.LivenessScore
	}
	return 0
}

func (x *FrameAnalysis) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *FrameAnalysis) GetAnalysis() *LivenessAnalysis {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// Sequence-level analysis results.
type SequenceAnalysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Temporal consistency score.
	TemporalConsistency float32 `protobuf:"fixed32,1,opt,name=temporal_consistency,json=temporalConsistency,proto3" json:"temporal_consistency,omitempty"`
	// Action completion scores.
	ActionCompletionScores map[string]float32 `protobuf:"bytes,2,rep,name=action_completion_scores,json=actionCompletionScores,proto3" json:"action_completion_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// Overall sequence quality.
	SequenceQuality float32 `protobuf:"fixed32,3,opt,name=sequence_quality,json=sequenceQuality,proto3" json:"sequence_quality,omitempty"`
	// Detected user actions.
	DetectedActions []string `protobuf:"bytes,4,rep,name=detected_actions,json=detectedActions,proto3" json:"detected_actions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SequenceAnalysis) Reset() {
	*x = SequenceAnalysis{}
	mi := &file_liveness_v1_liveness_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceAnalysis) ProtoMessage() {}

func (x *SequenceAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_liveness_v1_liveness_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceAnalysis.ProtoReflect.Descriptor instead.
func (*SequenceAnalysis) Descriptor() ([]byte, []int) {
	return file_liveness_v1_liveness_proto_rawDescGZIP(), []int{11}
}

func (x *SequenceAnalysis) GetTemporalConsistency() float32 {
	if x != nil {
		return x.TemporalConsistency
	}
	return 0
}

func (x *SequenceAnalysis) GetActionCompletionScores() map[string]float32 {
	if x != nil {
		return x.ActionCompletionScores
	}
	return nil
}

func (x *SequenceAnalysis) GetSequenceQuality() float32 {
	if x != nil {
		return x.SequenceQuality
	}
	return 0
}

func (x *SequenceAnalysis) GetDetectedActions() []string {
	if x != nil {
		return x.DetectedActions
	}
	return nil
}

var File_liveness_v1_liveness_proto protoreflect.FileDescriptor

const file_liveness_v1_liveness_proto_rawDesc = "" +
	"\n" +
	"\x1aliveness/v1/liveness.proto\x12\x15minakenta.liveness.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\xa7\x01\n" +
	"\x15DetectLivenessRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12%\n" +
	"\x0echallenge_type\x18\x03 \x01(\tR\rchallengeType\x12)\n" +
	"\x10expected_actions\x18\x04 \x03(\tR\x0fexpectedActions\"\xcd\x02\n" +
	"\x16DetectLivenessResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.minakenta.common.v1.ProcessingStatusR\x06status\x12%\n" +
	"\x0eliveness_score\x18\x02 \x01(\x02R\rlivenessScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12C\n" +
	"\banalysis\x18\x04 \x01(\v2'.minakenta.liveness.v1.LivenessAnalysisR\banalysis\x12C\n" +
	"\bmetadata\x18\x05 \x01(\v2'.minakenta.common.v1.ProcessingMetadataR\bmetadata\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\xb8\x03\n" +
	"\x10LivenessAnalysis\x12K\n" +
	"\x0eface_detection\x18\x01 \x01(\v2$.minakenta.liveness.v1.FaceDetectionR\rfaceDetection\x12W\n" +
	"\x12spoofing_detection\x18\x02 \x01(\v2(.minakenta.liveness.v1.SpoofingDetectionR\x11spoofingDetection\x12N\n" +
	"\x0fmotion_analysis\x18\x03 \x01(\v2%.minakenta.liveness.v1.MotionAnalysisR\x0emotionAnalysis\x12W\n" +
	"\x12quality_assessment\x18\x04 \x01(\v2(.minakenta.liveness.v1.QualityAssessmentR\x11qualityAssessment\x12U\n" +
	"\x10attack_detection\x18\x05 \x01(\v2*.minakenta.liveness.v1.AttackTypeDetectionR\x0fattackDetection\"\xaa\x01\n" +
	"\rFaceDetection\x12#\n" +
	"\rface_detected\x18\x01 \x01(\bR\ffaceDetected\x121\n" +
	"\x14detection_confidence\x18\x02 \x01(\x02R\x13detectionConfidence\x12A\n" +
	"\vface_bounds\x18\x03 \x01(\v2 .minakenta.common.v1.BoundingBoxR\n" +
	"faceBounds\"\xac\x02\n" +
	"\x11SpoofingDetection\x121\n" +
	"\x14spoofing_probability\x18\x01 \x01(\x02R\x13spoofingProbability\x12)\n" +
	"\x10detected_methods\x18\x02 \x03(\tR\x0fdetectedMethods\x12r\n" +
	"\x14anti_spoofing_scores\x18\x03 \x03(\v2@.minakenta.liveness.v1.SpoofingDetection.AntiSpoofingScoresEntryR\x12antiSpoofingScores\x1aE\n" +
	"\x17AntiSpoofingScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"}\n" +
	"\x0eMotionAnalysis\x12'\n" +
	"\x0fmotion_detected\x18\x01 \x01(\bR\x0emotionDetected\x12!\n" +
	"\fmotion_score\x18\x02 \x01(\x02R\vmotionScore\x12\x1f\n" +
	"\vmotion_type\x18\x03 \x01(\tR\n" +
	"motionType\"\xff\x01\n" +
	"\x11QualityAssessment\x12'\n" +
	"\x0foverall_quality\x18\x01 \x01(\x02R\x0eoverallQuality\x12)\n" +
	"\x10brightness_score\x18\x02 \x01(\x02R\x0fbrightnessScore\x12'\n" +
	"\x0fsharpness_score\x18\x03 \x01(\x02R\x0esharpnessScore\x12%\n" +
	"\x0econtrast_score\x18\x04 \x01(\x02R\rcontrastScore\x12\x1f\n" +
	"\vnoise_score\x18\x05 \x01(\x02R\n" +
	"noiseScore\x12%\n" +
	"\x0equality_issues\x18\x06 \x03(\tR\rqualityIssues\"\x8e\x02\n" +
	"\x13AttackTypeDetection\x12.\n" +
	"\x13primary_attack_type\x18\x01 \x01(\tR\x11primaryAttackType\x12}\n" +
	"\x17attack_type_confidences\x18\x02 \x03(\v2E.minakenta.liveness.v1.AttackTypeDetection.AttackTypeConfidencesEntryR\x15attackTypeConfidences\x1aH\n" +
	"\x1aAttackTypeConfidencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xdd\x01\n" +
	"\x1bAnalyzeVideoSequenceRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x02 \x03(\fR\tframeData\x12.\n" +
	"\x13frame_timestamps_ms\x18\x03 \x03(\x03R\x11frameTimestampsMs\x12%\n" +
	"\x0echallenge_type\x18\x04 \x01(\tR\rchallengeType\x12)\n" +
	"\x10expected_actions\x18\x05 \x03(\tR\x0fexpectedActions\"\xb1\x03\n" +
	"\x1cAnalyzeVideoSequenceResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.minakenta.common.v1.ProcessingStatusR\x06status\x12%\n" +
	"\x0eliveness_score\x18\x02 \x01(\x02R\rlivenessScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12K\n" +
	"\x0eframe_analyses\x18\x04 \x03(\v2$.minakenta.liveness.v1.FrameAnalysisR\rframeAnalyses\x12T\n" +
	"\x11sequence_analysis\x18\x05 \x01(\v2'.minakenta.liveness.v1.SequenceAnalysisR\x10sequenceAnalysis\x12C\n" +
	"\bmetadata\x18\x06 \x01(\v2'.minakenta.common.v1.ProcessingMetadataR\bmetadata\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"\xbc\x01\n" +
	"\rFrameAnalysis\x12\x1f\n" +
	"\vframe_index\x18\x01 \x01(\x05R\n" +
	"frameIndex\x12%\n" +
	"\x0eliveness_score\x18\x02 \x01(\x02R\rlivenessScore\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12C\n" +
	"\banalysis\x18\x04 \x01(\v2'.minakenta.liveness.v1.LivenessAnalysisR\banalysis\"\xe5\x02\n" +
	"\x10SequenceAnalysis\x121\n" +
	"\x14temporal_consistency\x18\x01 \x01(\x02R\x13temporalConsistency\x12}\n" +
	"\x18action_completion_scores\x18\x02 \x03(\v2C.minakenta.liveness.v1.SequenceAnalysis.ActionCompletionScoresEntryR\x16actionCompletionScores\x12)\n" +
	"\x10sequence_quality\x18\x03 \x01(\x02R\x0fsequenceQuality\x12)\n" +
	"\x10detected_actions\x18\x04 \x03(\tR\x0fdetectedActions\x1aI\n" +
	"\x1bActionCompletionScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x012\x81\x02\n" +
	"\x0fLivenessService\x12m\n" +
	"\x0eDetectLiveness\x12,.minakenta.liveness.v1.DetectLivenessRequest\x1a-.minakenta.liveness.v1.DetectLivenessResponse\x12\x7f\n" +
	"\x14AnalyzeVideoSequence\x122.minakenta.liveness.v1.AnalyzeVideoSequenceRequest\x1a3.minakenta.liveness.v1.AnalyzeVideoSequenceResponseB\xdc\x01\n" +
	"\x19com.minakenta.liveness.v1B\rLivenessProtoP\x01Z:github.com/Samimelki/minak-enta/api/liveness/v1;livenessv1\xa2\x02\x03MLX\xaa\x02\x15Minakenta.Liveness.V1\xca\x02\x15Minakenta\\Liveness\\V1\xe2\x02!Minakenta\\Liveness\\V1\\GPBMetadata\xea\x02\x17Minakenta::Liveness::V1b\x06proto3"

var (
	file_liveness_v1_liveness_proto_rawDescOnce sync.Once
	file_liveness_v1_liveness_proto_rawDescData []byte
)

func file_liveness_v1_liveness_proto_rawDescGZIP() []byte {
	file_liveness_v1_liveness_proto_rawDescOnce.Do(func() {
		file_liveness_v1_liveness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_liveness_v1_liveness_proto_rawDesc), len(file_liveness_v1_liveness_proto_rawDesc)))
	})
	return file_liveness_v1_liveness_proto_rawDescData
}

var file_liveness_v1_liveness_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_liveness_v1_liveness_proto_goTypes = []any{
	(*DetectLivenessRequest)(nil),        // 0: minakenta.liveness.v1.DetectLivenessRequest
	(*DetectLivenessResponse)(nil),       // 1: minakenta.liveness.v1.DetectLivenessResponse
	(*LivenessAnalysis)(nil),             // 2: minakenta.liveness.v1.LivenessAnalysis
	(*FaceDetection)(nil),                // 3: minakenta.liveness.v1.FaceDetection
	(*SpoofingDetection)(nil),            // 4: minakenta.liveness.v1.SpoofingDetection
	(*MotionAnalysis)(nil),               // 5: minakenta.liveness.v1.MotionAnalysis
	(*QualityAssessment)(nil),            // 6: minakenta.liveness.v1.QualityAssessment
	(*AttackTypeDetection)(nil),          // 7: minakenta.liveness.v1.AttackTypeDetection
	(*AnalyzeVideoSequenceRequest)(nil),  // 8: minakenta.liveness.v1.AnalyzeVideoSequenceRequest
	(*AnalyzeVideoSequenceResponse)(nil), // 9: minakenta.liveness.v1.AnalyzeVideoSequenceResponse
	(*FrameAnalysis)(nil),                // 10: minakenta.liveness.v1.FrameAnalysis
	(*SequenceAnalysis)(nil),             // 11: minakenta.liveness.v1.SequenceAnalysis
	nil,                                  // 12: minakenta.liveness.v1.SpoofingDetection.AntiSpoofingScoresEntry
	nil,                                  // 13: minakenta.liveness.v1.AttackTypeDetection.AttackTypeConfidencesEntry
	nil,                                  // 14: minakenta.liveness.v1.SequenceAnalysis.ActionCompletionScoresEntry
	(v1.ProcessingStatus)(0),             // 15: minakenta.common.v1.ProcessingStatus
	(*v1.ProcessingMetadata)(nil),        // 16: minakenta.common.v1.ProcessingMetadata
	(*v1.BoundingBox)(nil),               // 17: minakenta.common.v1.BoundingBox
}
var file_liveness_v1_liveness_proto_depIdxs = []int32{
	15, // 0: minakenta.liveness.v1.DetectLivenessResponse.status:type_name -> minakenta.common.v1.ProcessingStatus
	2,  // 1: minakenta.liveness.v1.DetectLivenessResponse.analysis:type_name -> minakenta.liveness.v1.LivenessAnalysis
	16, // 2: minakenta.liveness.v1.DetectLivenessResponse.metadata:type_name -> minakenta.common.v1.ProcessingMetadata
	3,  // 3: minakenta.liveness.v1.LivenessAnalysis.face_detection:type_name -> minakenta.liveness.v1.FaceDetection
	4,  // 4: minakenta.liveness.v1.LivenessAnalysis.spoofing_detection:type_name -> minakenta.liveness.v1.SpoofingDetection
	5,  // 5: minakenta.liveness.v1.LivenessAnalysis.motion_analysis:type_name -> minakenta.liveness.v1.MotionAnalysis
	6,  // 6: minakenta.liveness.v1.LivenessAnalysis.quality_assessment:type_name -> minakenta.liveness.v1.QualityAssessment
	7,  // 7: minakenta.liveness.v1.LivenessAnalysis.attack_detection:type_name -> minakenta.liveness.v1.AttackTypeDetection
	17, // 8: minakenta.liveness.v1.FaceDetection.face_bounds:type_name -> minakenta.common.v1.BoundingBox
	12, // 9: minakenta.liveness.v1.SpoofingDetection.anti_spoofing_scores:type_name -> minakenta.liveness.v1.SpoofingDetection.AntiSpoofingScoresEntry
	13, // 10: minakenta.liveness.v1.AttackTypeDetection.attack_type_confidences:type_name -> minakenta.liveness.v1.AttackTypeDetection.AttackTypeConfidencesEntry
	15, // 11: minakenta.liveness.v1.AnalyzeVideoSequenceResponse.status:type_name -> minakenta.common.v1.ProcessingStatus
	10, // 12: minakenta.liveness.v1.AnalyzeVideoSequenceResponse.frame_analyses:type_name -> minakenta.liveness.v1.FrameAnalysis
	11, // 13: minakenta.liveness.v1.AnalyzeVideoSequenceResponse.sequence_analysis:type_name -> minakenta.liveness.v1.SequenceAnalysis
	16, // 14: minakenta.liveness.v1.AnalyzeVideoSequenceResponse.metadata:type_name -> minakenta.common.v1.ProcessingMetadata
	2,  // 15: minakenta.liveness.v1.FrameAnalysis.analysis:type_name -> minakenta.liveness.v1.LivenessAnalysis
	14, // 16: minakenta.liveness.v1.SequenceAnalysis.action_completion_scores:type_name -> minakenta.liveness.v1.SequenceAnalysis.ActionCompletionScoresEntry
	0,  // 17: minakenta.liveness.v1.LivenessService.DetectLiveness:input_type -> minakenta.liveness.v1.DetectLivenessRequest
	8,  // 18: minakenta.liveness.v1.LivenessService.AnalyzeVideoSequence:input_type -> minakenta.liveness.v1.AnalyzeVideoSequenceRequest
	1,  // 19: minakenta.liveness.v1.LivenessService.DetectLiveness:output_type -> minakenta.liveness.v1.DetectLivenessResponse
	9,  // 20: minakenta.liveness.v1.LivenessService.AnalyzeVideoSequence:output_type -> minakenta.liveness.v1.AnalyzeVideoSequenceResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_liveness_v1_liveness_proto_init() }
func file_liveness_v1_liveness_proto_init() {
	if File_liveness_v1_liveness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_liveness_v1_liveness_proto_rawDesc), len(file_liveness_v1_liveness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_liveness_v1_liveness_proto_goTypes,
		DependencyIndexes: file_liveness_v1_liveness_proto_depIdxs,
		MessageInfos:      file_liveness_v1_liveness_proto_msgTypes,
	}.Build()
	File_liveness_v1_liveness_proto = out.File
	file_liveness_v1_liveness_proto_goTypes = nil
	file_liveness_v1_liveness_proto_depIdxs = nil
}
