// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ocr/v1/ocr.proto

package ocrv1

import (
	v1 "github.com/Samimelki/minak-enta/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported document types.
type DocumentType int32

const (
	DocumentType_DOCUMENT_TYPE_UNSPECIFIED       DocumentType = 0
	DocumentType_DOCUMENT_TYPE_LEBANESE_ID_FRONT DocumentType = 1
	DocumentType_DOCUMENT_TYPE_LEBANESE_ID_BACK  DocumentType = 2
)

// Enum value maps for DocumentType.
var (
	DocumentType_name = map[int32]string{
		0: "DOCUMENT_TYPE_UNSPECIFIED",
		1: "DOCUMENT_TYPE_LEBANESE_ID_FRONT",
		2: "DOCUMENT_TYPE_LEBANESE_ID_BACK",
	}
	DocumentType_value = map[string]int32{
		"DOCUMENT_TYPE_UNSPECIFIED":       0,
		"DOCUMENT_TYPE_LEBANESE_ID_FRONT": 1,
		"DOCUMENT_TYPE_LEBANESE_ID_BACK":  2,
	}
)

func (x DocumentType) Enum() *DocumentType {
	p := new(DocumentType)
	*p = x
	return p
}

func (x DocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_ocr_v1_ocr_proto_enumTypes[0].Descriptor()
}

func (DocumentType) Type() protoreflect.EnumType {
	return &file_ocr_v1_ocr_proto_enumTypes[0]
}

func (x DocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentType.Descriptor instead.
func (DocumentType) EnumDescriptor() ([]byte, []int) {
	return file_ocr_v1_ocr_proto_rawDescGZIP(), []int{0}
}

// Request to process a document.
type ProcessDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Document image data (JPEG or PNG).
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// Document type to guide OCR processing.
	DocumentType DocumentType `protobuf:"varint,3,opt,name=document_type,json=documentType,proto3,enum=minakenta.ocr.v1.DocumentType" json:"document_type,omitempty"`
	// Expected language hints (e.g., "ara" for Arabic, "lat" for Latin).
	LanguageHints []string `protobuf:"bytes,4,rep,name=language_hints,json=languageHints,proto3" json:"language_hints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentRequest) Reset() {
	*x = ProcessDocumentRequest{}
	mi := &file_ocr_v1_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentRequest) ProtoMessage() {}

func (x *ProcessDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_v1_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentRequest.ProtoReflect.Descriptor instead.
func (*ProcessDocumentRequest) Descriptor() ([]byte, []int) {
	return file_ocr_v1_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessDocumentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessDocumentRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ProcessDocumentRequest) GetDocumentType() DocumentType {
	if x != nil {
		return x.DocumentType
	}
	return DocumentType_DOCUMENT_TYPE_UNSPECIFIED
}

func (x *ProcessDocumentRequest) GetLanguageHints() []string {
	if x != nil {
		return x.LanguageHints
	}
	return nil
}

// Response from document processing.
type ProcessDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processing status.
	Status v1.ProcessingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=minakenta.common.v1.ProcessingStatus" json:"status,omitempty"`
	// Overall confidence score (0-100).
	ConfidenceScore float32 `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	// Extracted structured data.
	ExtractedData *ExtractedData `protobuf:"bytes,3,opt,name=extracted_data,json=extractedData,proto3" json:"extracted_data,omitempty"`
	// Detailed confidence scores for individual fields.
	FieldConfidences *FieldConfidences `protobuf:"bytes,4,opt,name=field_confidences,json=fieldConfidences,proto3" json:"field_confidences,omitempty"`
	// Processing metadata.
	Metadata *v1.ProcessingMetadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Error details if processing failed.
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDocumentResponse) Reset() {
	*x = ProcessDocumentResponse{}
	mi := &file_ocr_v1_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDocumentResponse) ProtoMessage() {}

func (x *ProcessDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_v1_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDocumentResponse.ProtoReflect.Descriptor instead.
func (*ProcessDocumentResponse) Descriptor() ([]byte, []int) {
	return file_ocr_v1_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessDocumentResponse) GetStatus() v1.ProcessingStatus {
	if x != nil {
		return x.Status
	}
	return v1.ProcessingStatus(0)
}

func (x *ProcessDocumentResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *ProcessDocumentResponse) GetExtractedData() *ExtractedData {
	if x != nil {
		return x.ExtractedData
	}
	return nil
}

func (x *ProcessDocumentResponse) GetFieldConfidences() *FieldConfidences {
	if x != nil {
		return x.FieldConfidences
	}
	return nil
}

func (x *ProcessDocumentResponse) GetMetadata() *v1.ProcessingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ProcessDocumentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Structured data extracted from the document.
type ExtractedData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Personal information.
	NameArabic  string `protobuf:"bytes,1,opt,name=name_arabic,json=nameArabic,proto3" json:"name_arabic,omitempty"`
	NameLatin   string `protobuf:"bytes,2,opt,name=name_latin,json=nameLatin,proto3" json:"name_latin,omitempty"`
	DateOfBirth string `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"` // ISO 8601 format: YYYY-MM-DD
	IdNumber    string `protobuf:"bytes,4,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	Gender      string `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"` // "male" or "female"
	Nationality string `protobuf:"bytes,6,opt,name=nationality,proto3" json:"nationality,omitempty"`
	// Document information.
	DocumentNumber   string `protobuf:"bytes,7,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"`
	IssueDate        string `protobuf:"bytes,8,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`    // ISO 8601 format: YYYY-MM-DD
	ExpiryDate       string `protobuf:"bytes,9,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"` // ISO 8601 format: YYYY-MM-DD
	IssuingAuthority string `protobuf:"bytes,10,opt,name=issuing_authority,json=issuingAuthority,proto3" json:"issuing_authority,omitempty"`
	// Additional extracted fields (may be empty).
	AdditionalFields map[string]string `protobuf:"bytes,11,rep,name=additional_fields,json=additionalFields,proto3" json:"additional_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtractedData) Reset() {
	*x = ExtractedData{}
	mi := &file_ocr_v1_ocr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractedData) ProtoMessage() {}

func (x *ExtractedData) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_v1_ocr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractedData.ProtoReflect.Descriptor instead.
func (*ExtractedData) Descriptor() ([]byte, []int) {
	return file_ocr_v1_ocr_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractedData) GetNameArabic() string {
	if x != nil {
		return x.NameArabic
	}
	return ""
}

func (x *ExtractedData) GetNameLatin() string {
	if x != nil {
		return x.NameLatin
	}
	return ""
}

func (x *ExtractedData) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *ExtractedData) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *ExtractedData) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ExtractedData) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *ExtractedData) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *ExtractedData) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

func (x *ExtractedData) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *ExtractedData) GetIssuingAuthority() string {
	if x != nil {
		return x.IssuingAuthority
	}
	return ""
}

func (x *ExtractedData) GetAdditionalFields() map[string]string {
	if x != nil {
		return x.AdditionalFields
	}
	return nil
}

// Confidence scores for individual fields.
type FieldConfidences struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	NameArabicConfidence       float32                `protobuf:"fixed32,1,opt,name=name_arabic_confidence,json=nameArabicConfidence,proto3" json:"name_arabic_confidence,omitempty"`
	NameLatinConfidence        float32                `protobuf:"fixed32,2,opt,name=name_latin_confidence,json=nameLatinConfidence,proto3" json:"name_latin_confidence,omitempty"`
	DateOfBirthConfidence      float32                `protobuf:"fixed32,3,opt,name=date_of_birth_confidence,json=dateOfBirthConfidence,proto3" json:"date_of_birth_confidence,omitempty"`
	IdNumberConfidence         float32                `protobuf:"fixed32,4,opt,name=id_number_confidence,json=idNumberConfidence,proto3" json:"id_number_confidence,omitempty"`
	GenderConfidence           float32                `protobuf:"fixed32,5,opt,name=gender_confidence,json=genderConfidence,proto3" json:"gender_confidence,omitempty"`
	NationalityConfidence      float32                `protobuf:"fixed32,6,opt,name=nationality_confidence,json=nationalityConfidence,proto3" json:"nationality_confidence,omitempty"`
	DocumentNumberConfidence   float32                `protobuf:"fixed32,7,opt,name=document_number_confidence,json=documentNumberConfidence,proto3" json:"document_number_confidence,omitempty"`
	IssueDateConfidence        float32                `protobuf:"fixed32,8,opt,name=issue_date_confidence,json=issueDateConfidence,proto3" json:"issue_date_confidence,omitempty"`
	ExpiryDateConfidence       float32                `protobuf:"fixed32,9,opt,name=expiry_date_confidence,json=expiryDateConfidence,proto3" json:"expiry_date_confidence,omitempty"`
	IssuingAuthorityConfidence float32                `protobuf:"fixed32,10,opt,name=issuing_authority_confidence,json=issuingAuthorityConfidence,proto3" json:"issuing_authority_confidence,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *FieldConfidences) Reset() {
	*x = FieldConfidences{}
	mi := &file_ocr_v1_ocr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldConfidences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldConfidences) ProtoMessage() {}

func (x *FieldConfidences) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_v1_ocr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldConfidences.ProtoReflect.Descriptor instead.
func (*FieldConfidences) Descriptor() ([]byte, []int) {
	return file_ocr_v1_ocr_proto_rawDescGZIP(), []int{3}
}

func (x *FieldConfidences) GetNameArabicConfidence() float32 {
	if x != nil {
		return x.NameArabicConfidence
	}
	return 0
}

func (x *FieldConfidences) GetNameLatinConfidence() float32 {
	if x != nil {
		return x.NameLatinConfidence
	}
	return 0
}

func (x *FieldConfidences) GetDateOfBirthConfidence() float32 {
	if x != nil {
		return x.DateOfBirthConfidence
	}
	return 0
}

func (x *FieldConfidences) GetIdNumberConfidence() float32 {
	if x != nil {
		return x.IdNumberConfidence
	}
	return 0
}

func (x *FieldConfidences) GetGenderConfidence() float32 {
	if x != nil {
		return x.GenderConfidence
	}
	return 0
}

func (x *FieldConfidences) GetNationalityConfidence() float32 {
	if x != nil {
		return x.NationalityConfidence
	}
	return 0
}

func (x *FieldConfidences) GetDocumentNumberConfidence() float32 {
	if x != nil {
		return x.DocumentNumberConfidence
	}
	return 0
}

func (x *FieldConfidences) GetIssueDateConfidence() float32 {
	if x != nil {
		return x.IssueDateConfidence
	}
	return 0
}

func (x *FieldConfidences) GetExpiryDateConfidence() float32 {
	if x != nil {
		return x.ExpiryDateConfidence
	}
	return 0
}

func (x *FieldConfidences) GetIssuingAuthorityConfidence() float32 {
	if x != nil {
		return x.IssuingAuthorityConfidence
	}
	return 0
}

var File_ocr_v1_ocr_proto protoreflect.FileDescriptor

const file_ocr_v1_ocr_proto_rawDesc = "" +
	"\n" +
	"\x10ocr/v1/ocr.proto\x12\x10minakenta.ocr.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/v1/common.proto\"\xc2\x01\n" +
	"\x16ProcessDocumentRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12C\n" +
	"\rdocument_type\x18\x03 \x01(\x0e2\x1e.minakenta.ocr.v1.DocumentTypeR\fdocumentType\x12%\n" +
	"\x0elanguage_hints\x18\x04 \x03(\tR\rlanguageHints\"\x86\x03\n" +
	"\x17ProcessDocumentResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.minakenta.common.v1.ProcessingStatusR\x06status\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12F\n" +
	"\x0eextracted_data\x18\x03 \x01(\v2\x1f.minakenta.ocr.v1.ExtractedDataR\rextractedData\x12O\n" +
	"\x11field_confidences\x18\x04 \x01(\v2\".minakenta.ocr.v1.FieldConfidencesR\x10fieldConfidences\x12C\n" +
	"\bmetadata\x18\x05 \x01(\v2'.minakenta.common.v1.ProcessingMetadataR\bmetadata\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"\x89\x04\n" +
	"\rExtractedData\x12\x1f\n" +
	"\vname_arabic\x18\x01 \x01(\tR\n" +
	"nameArabic\x12\x1d\n" +
	"\n" +
	"name_latin\x18\x02 \x01(\tR\tnameLatin\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\x12\x1b\n" +
	"\tid_number\x18\x04 \x01(\tR\bidNumber\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12 \n" +
	"\vnationality\x18\x06 \x01(\tR\vnationality\x12'\n" +
	"\x0fdocument_number\x18\a \x01(\tR\x0edocumentNumber\x12\x1d\n" +
	"\n" +
	"issue_date\x18\b \x01(\tR\tissueDate\x12\x1f\n" +
	"\vexpiry_date\x18\t \x01(\tR\n" +
	"expiryDate\x12+\n" +
	"\x11issuing_authority\x18\n" +
	" \x01(\tR\x10issuingAuthority\x12b\n" +
	"\x11additional_fields\x18\v \x03(\v25.minakenta.ocr.v1.ExtractedData.AdditionalFieldsEntryR\x10additionalFields\x1aC\n" +
	"\x15AdditionalFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x04\n" +
	"\x10FieldConfidences\x124\n" +
	"\x16name_arabic_confidence\x18\x01 \x01(\x02R\x14nameArabicConfidence\x122\n" +
	"\x15name_latin_confidence\x18\x02 \x01(\x02R\x13nameLatinConfidence\x127\n" +
	"\x18date_of_birth_confidence\x18\x03 \x01(\x02R\x15dateOfBirthConfidence\x120\n" +
	"\x14id_number_confidence\x18\x04 \x01(\x02R\x12idNumberConfidence\x12+\n" +
	"\x11gender_confidence\x18\x05 \x01(\x02R\x10genderConfidence\x125\n" +
	"\x16nationality_confidence\x18\x06 \x01(\x02R\x15nationalityConfidence\x12<\n" +
	"\x1adocument_number_confidence\x18\a \x01(\x02R\x18documentNumberConfidence\x122\n" +
	"\x15issue_date_confidence\x18\b \x01(\x02R\x13issueDateConfidence\x124\n" +
	"\x16expiry_date_confidence\x18\t \x01(\x02R\x14expiryDateConfidence\x12@\n" +
	"\x1cissuing_authority_confidence\x18\n" +
	" \x01(\x02R\x1aissuingAuthorityConfidence*v\n" +
	"\fDocumentType\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDOCUMENT_TYPE_LEBANESE_ID_FRONT\x10\x01\x12\"\n" +
	"\x1eDOCUMENT_TYPE_LEBANESE_ID_BACK\x10\x022t\n" +
	"\n" +
	"OCRService\x12f\n" +
	"\x0fProcessDocument\x12(.minakenta.ocr.v1.ProcessDocumentRequest\x1a).minakenta.ocr.v1.ProcessDocumentResponseB\xb4\x01\n" +
	"\x14com.minakenta.ocr.v1B\bOcrProtoP\x01Z0github.com/Samimelki/minak-enta/api/ocr/v1;ocrv1\xa2\x02\x03MOX\xaa\x02\x10Minakenta.Ocr.V1\xca\x02\x10Minakenta\\Ocr\\V1\xe2\x02\x1cMinakenta\\Ocr\\V1\\GPBMetadata\xea\x02\x12Minakenta::Ocr::V1b\x06proto3"

var (
	file_ocr_v1_ocr_proto_rawDescOnce sync.Once
	file_ocr_v1_ocr_proto_rawDescData []byte
)

func file_ocr_v1_ocr_proto_rawDescGZIP() []byte {
	file_ocr_v1_ocr_proto_rawDescOnce.Do(func() {
		file_ocr_v1_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocr_v1_ocr_proto_rawDesc), len(file_ocr_v1_ocr_proto_rawDesc)))
	})
	return file_ocr_v1_ocr_proto_rawDescData
}

var file_ocr_v1_ocr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ocr_v1_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ocr_v1_ocr_proto_goTypes = []any{
	(DocumentType)(0),               // 0: minakenta.ocr.v1.DocumentType
	(*ProcessDocumentRequest)(nil),  // 1: minakenta.ocr.v1.ProcessDocumentRequest
	(*ProcessDocumentResponse)(nil), // 2: minakenta.ocr.v1.ProcessDocumentResponse
	(*ExtractedData)(nil),           // 3: minakenta.ocr.v1.ExtractedData
	(*FieldConfidences)(nil),        // 4: minakenta.ocr.v1.FieldConfidences
	nil,                             // 5: minakenta.ocr.v1.ExtractedData.AdditionalFieldsEntry
	(v1.ProcessingStatus)(0),        // 6: minakenta.common.v1.ProcessingStatus
	(*v1.ProcessingMetadata)(nil),   // 7: minakenta.common.v1.ProcessingMetadata
}
var file_ocr_v1_ocr_proto_depIdxs = []int32{
	0, // 0: minakenta.ocr.v1.ProcessDocumentRequest.document_type:type_name -> minakenta.ocr.v1.DocumentType
	6, // 1: minakenta.ocr.v1.ProcessDocumentResponse.status:type_name -> minakenta.common.v1.ProcessingStatus
	3, // 2: minakenta.ocr.v1.ProcessDocumentResponse.extracted_data:type_name -> minakenta.ocr.v1.ExtractedData
	4, // 3: minakenta.ocr.v1.ProcessDocumentResponse.field_confidences:type_name -> minakenta.ocr.v1.FieldConfidences
	7, // 4: minakenta.ocr.v1.ProcessDocumentResponse.metadata:type_name -> minakenta.common.v1.ProcessingMetadata
	5, // 5: minakenta.ocr.v1.ExtractedData.additional_fields:type_name -> minakenta.ocr.v1.ExtractedData.AdditionalFieldsEntry
	1, // 6: minakenta.ocr.v1.OCRService.ProcessDocument:input_type -> minakenta.ocr.v1.ProcessDocumentRequest
	2, // 7: minakenta.ocr.v1.OCRService.ProcessDocument:output_type -> minakenta.ocr.v1.ProcessDocumentResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ocr_v1_ocr_proto_init() }
func file_ocr_v1_ocr_proto_init() {
	if File_ocr_v1_ocr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocr_v1_ocr_proto_rawDesc), len(file_ocr_v1_ocr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocr_v1_ocr_proto_goTypes,
		DependencyIndexes: file_ocr_v1_ocr_proto_depIdxs,
		EnumInfos:         file_ocr_v1_ocr_proto_enumTypes,
		MessageInfos:      file_ocr_v1_ocr_proto_msgTypes,
	}.Build()
	File_ocr_v1_ocr_proto = out.File
	file_ocr_v1_ocr_proto_goTypes = nil
	file_ocr_v1_ocr_proto_depIdxs = nil
}
