// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: ocr/v1/ocr.proto

package ocrv1

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// OCRServiceServer is the server API for OCRService service.
type OCRServiceServer interface {
	ProcessDocument(context.Context, *ProcessDocumentRequest) (*ProcessDocumentResponse, error)
}

// RegisterOCRServiceServer registers the HTTP handlers for service OCRService to the given mux.
func RegisterOCRServiceServer(server OCRServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getOCRServiceHeaders()

	methodHeaders := getProcessDocumentHeaders()
	processDocumentHandler := BindingMiddleware[ProcessDocumentRequest](
		genericHandler(server.ProcessDocument), serviceHeaders, methodHeaders,
	)

	config.mux.Handle("POST /ocrv1/process_document", processDocumentHandler)

	return nil
}

// getOCRServiceHeaders returns the service-level required headers for OCRService
func getOCRServiceHeaders() []*sebufhttp.Header {
	return nil
}

// getProcessDocumentHeaders returns the method-level required headers for ProcessDocument
func getProcessDocumentHeaders() []*sebufhttp.Header {
	return nil
}
