// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common processing status used across all ML services
type ProcessingStatus int32

const (
	ProcessingStatus_PROCESSING_STATUS_UNSPECIFIED             ProcessingStatus = 0
	ProcessingStatus_PROCESSING_STATUS_SUCCESS                 ProcessingStatus = 1
	ProcessingStatus_PROCESSING_STATUS_FAILED                  ProcessingStatus = 2
	ProcessingStatus_PROCESSING_STATUS_LOW_CONFIDENCE          ProcessingStatus = 3
	ProcessingStatus_PROCESSING_STATUS_NO_FACE_DETECTED        ProcessingStatus = 4
	ProcessingStatus_PROCESSING_STATUS_MULTIPLE_FACES_DETECTED ProcessingStatus = 5
	ProcessingStatus_PROCESSING_STATUS_LOW_QUALITY_IMAGE       ProcessingStatus = 6
	ProcessingStatus_PROCESSING_STATUS_INSUFFICIENT_FRAMES     ProcessingStatus = 7
)

// Enum value maps for ProcessingStatus.
var (
	ProcessingStatus_name = map[int32]string{
		0: "PROCESSING_STATUS_UNSPECIFIED",
		1: "PROCESSING_STATUS_SUCCESS",
		2: "PROCESSING_STATUS_FAILED",
		3: "PROCESSING_STATUS_LOW_CONFIDENCE",
		4: "PROCESSING_STATUS_NO_FACE_DETECTED",
		5: "PROCESSING_STATUS_MULTIPLE_FACES_DETECTED",
		6: "PROCESSING_STATUS_LOW_QUALITY_IMAGE",
		7: "PROCESSING_STATUS_INSUFFICIENT_FRAMES",
	}
	ProcessingStatus_value = map[string]int32{
		"PROCESSING_STATUS_UNSPECIFIED":             0,
		"PROCESSING_STATUS_SUCCESS":                 1,
		"PROCESSING_STATUS_FAILED":                  2,
		"PROCESSING_STATUS_LOW_CONFIDENCE":          3,
		"PROCESSING_STATUS_NO_FACE_DETECTED":        4,
		"PROCESSING_STATUS_MULTIPLE_FACES_DETECTED": 5,
		"PROCESSING_STATUS_LOW_QUALITY_IMAGE":       6,
		"PROCESSING_STATUS_INSUFFICIENT_FRAMES":     7,
	}
)

func (x ProcessingStatus) Enum() *ProcessingStatus {
	p := new(ProcessingStatus)
	*p = x
	return p
}

func (x ProcessingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (ProcessingStatus) Type() protoreflect.EnumType {
	return &file_common_v1_common_proto_enumTypes[0]
}

func (x ProcessingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessingStatus.Descriptor instead.
func (ProcessingStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// 2D bounding box for detected regions
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// Common processing metadata included in all ML service responses
type ProcessingMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Processing duration in milliseconds
	ProcessingTimeMs int32 `protobuf:"varint,1,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	// Version of the model/engine used
	ModelVersion string `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	// Preprocessing or detection methods applied
	MethodsApplied []string `protobuf:"bytes,3,rep,name=methods_applied,json=methodsApplied,proto3" json:"methods_applied,omitempty"`
	// Timestamp when processing was completed
	ProcessedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	// Additional metadata as key-value pairs
	AdditionalMetadata map[string]string `protobuf:"bytes,5,rep,name=additional_metadata,json=additionalMetadata,proto3" json:"additional_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessingMetadata) Reset() {
	*x = ProcessingMetadata{}
	mi := &file_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingMetadata) ProtoMessage() {}

func (x *ProcessingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingMetadata.ProtoReflect.Descriptor instead.
func (*ProcessingMetadata) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessingMetadata) GetProcessingTimeMs() int32 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

func (x *ProcessingMetadata) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ProcessingMetadata) GetMethodsApplied() []string {
	if x != nil {
		return x.MethodsApplied
	}
	return nil
}

func (x *ProcessingMetadata) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *ProcessingMetadata) GetAdditionalMetadata() map[string]string {
	if x != nil {
		return x.AdditionalMetadata
	}
	return nil
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\x13minakenta.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\x88\x03\n" +
	"\x12ProcessingMetadata\x12,\n" +
	"\x12processing_time_ms\x18\x01 \x01(\x05R\x10processingTimeMs\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x12'\n" +
	"\x0fmethods_applied\x18\x03 \x03(\tR\x0emethodsApplied\x12=\n" +
	"\fprocessed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12p\n" +
	"\x13additional_metadata\x18\x05 \x03(\v2?.minakenta.common.v1.ProcessingMetadata.AdditionalMetadataEntryR\x12additionalMetadata\x1aE\n" +
	"\x17AdditionalMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xc3\x02\n" +
	"\x10ProcessingStatus\x12!\n" +
	"\x1dPROCESSING_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PROCESSING_STATUS_SUCCESS\x10\x01\x12\x1c\n" +
	"\x18PROCESSING_STATUS_FAILED\x10\x02\x12$\n" +
	" PROCESSING_STATUS_LOW_CONFIDENCE\x10\x03\x12&\n" +
	"\"PROCESSING_STATUS_NO_FACE_DETECTED\x10\x04\x12-\n" +
	")PROCESSING_STATUS_MULTIPLE_FACES_DETECTED\x10\x05\x12'\n" +
	"#PROCESSING_STATUS_LOW_QUALITY_IMAGE\x10\x06\x12)\n" +
	"%PROCESSING_STATUS_INSUFFICIENT_FRAMES\x10\aB\xcc\x01\n" +
	"\x17com.minakenta.common.v1B\vCommonProtoP\x01Z6github.com/Samimelki/minak-enta/api/common/v1;commonv1\xa2\x02\x03MCX\xaa\x02\x13Minakenta.Common.V1\xca\x02\x13Minakenta\\Common\\V1\xe2\x02\x1fMinakenta\\Common\\V1\\GPBMetadata\xea\x02\x15Minakenta::Common::V1b\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_v1_common_proto_goTypes = []any{
	(ProcessingStatus)(0),         // 0: minakenta.common.v1.ProcessingStatus
	(*BoundingBox)(nil),           // 1: minakenta.common.v1.BoundingBox
	(*ProcessingMetadata)(nil),    // 2: minakenta.common.v1.ProcessingMetadata
	nil,                           // 3: minakenta.common.v1.ProcessingMetadata.AdditionalMetadataEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_common_v1_common_proto_depIdxs = []int32{
	4, // 0: minakenta.common.v1.ProcessingMetadata.processed_at:type_name -> google.protobuf.Timestamp
	3, // 1: minakenta.common.v1.ProcessingMetadata.additional_metadata:type_name -> minakenta.common.v1.ProcessingMetadata.AdditionalMetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		EnumInfos:         file_common_v1_common_proto_enumTypes,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
